### ISSUE TITLE
Extension crashes while downloading  

### ISSUE THREAD

**Issue by other-half** [Momo707577045/m3u8-downloader#47]
While downloading files of size about 3 GB or above, just before downloading the last segment the memory consumption increases to about twice the file size and the system become unresponsive.Also after some waiting the extension displays it crashed. I have a 8 GB RAM still I am facing problem with 3GB files.
Please look into this problem and resolve it.
I had a nice time using this extension.
Thank you.

**Comment by Momo707577045** [comment]
Thank you for your feedback

This problem is solved in the Chinese version of the tool. Large files can be downloaded in segments. Only due to limited energy, it was not synchronized to the English version.

As for why 3G video will crash when downloaded from 8g memory, it is probably the problem of system memory. In addition to video, the system also runs many other programs. It may also be the limitation of chrome memory management

**Comment by Momo707577045** [comment]
http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index.html
![image](https://user-images.githubusercontent.com/12947294/153530841-15da14db-41b6-4cc0-aaef-e42a478a1d1a.png)
![image](https://user-images.githubusercontent.com/12947294/153530924-6d447289-34b9-4373-ad0b-0a5b17862956.png)
